version: '3.0'

services:

  db:
    image: postgres:latest
    container_name: "cookie-bot-db"
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: cookie-bot
    networks:
      - cookie-bot
  
  adminer:
    image: adminer:latest
    container_name: "cookie-bot-adminer"
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - cookie-bot

networks:
  cookie-bot:
    driver: bridge
